name: Deploy API to Azure Web App

on:
  push:
    branches: [ "master" ]
    paths:
      - "server/**"
      - ".github/workflows/api-deploy.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: (Optional) Build
        run: npm run build || echo "skip build"

      - name: Zip artifact
        run: |
          cd ..
          zip -r api.zip server -x "server/node_modules/**" -x "server/.env"

      #  Login a Azure con Service Principal 
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: production
          package: api.zip
