name: Deploy Front to Azure Static Web Apps

on:
  push:
    branches: [ master ]
    paths:
      - 'client/**'
      - '.github/workflows/azure-static-web-apps.yml'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install deps (client)
        working-directory: client
        run: npm ci || npm install --force

      - name: Build (client)
        working-directory: client
        run: npm run build

      # Subimos SOLO lo compilado para evitar "too many static files"
      - name: Deploy (upload prebuilt dist)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: /             # requerido por el validador aunque no se use en 'upload'
          app_artifact_location: client/dist
