name: Deploy Front to Azure Static Web Apps

on:
  push:
    branches:
      - master
      - main
    paths:
      - "client/**"
      - ".github/workflows/azure-static-web-apps.yml"
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # ---- WORKAROUND ROLLUP / NPM OPTIONAL DEPS ----
      # 1) Intento normal con npm ci pero ignorando dependencias opcionales.
      - name: Install deps (ignore optional)
        working-directory: client
        run: npm ci
        env:
          npm_config_ignore_optional: "true"
        continue-on-error: true

      # 2) Si lo anterior falló, hacemos un fallback:
      #    limpiamos lockfile y cache y usamos npm install sin opcionales.
      - name: Fallback install (no lock, no optional)
        if: failure()
        working-directory: client
        run: |
          rm -f package-lock.json
          npm cache clean --force
          npm install --no-optional

      - name: Build
        working-directory: client
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "client"
          output_location: "dist"
